sudo: required

language: go

go:
 - 1.5
 - 1.6

services:
- docker

install:
- echo install

script:
- go version
- echo $CROSSDOCK

env:
  global:
    - GLOBAL_VAR=foo

matrix:
  include:
    - go: 1.5
      env: CROSSDOCK=1
