sudo: required

language: go

services:
- docker

install:
- echo install

script:
- go version
- echo $GLOBAL_VAR $FOO $BAR $FAZ $BOO

env:
  global:
    - GLOBAL_VAR=foo
  matrix:
    - FOO=true BAR=False

matrix:
  include:
    - go: 1.5
      env: FAZ=true BOO=False
    - go: 1.6
      env: env: FAZ=true BOO=true
